### ISSUE TITLE
Enhancement - Allow players to adjust stat upgrade pools past normal limits and to adjust how many levels they grant.

### ISSUE THREAD

**Issue by zViitorEXCELLENT** [ThePhar/RogueLegacyRandomizer#68]
**Current Behavior**
With the current settings we get x5 for every upgrade, such as:
Mana, Health, Attack and Magic Damage (pools of 75)
Equip Up and Armor Up (pools of 50)

**Improved Behavior**
We would have a new settings option to get x3 (for 75s) and x2 (for 50s) to make the game slower, so:
Mana, Health, Attack and Magic Damage would have 25 upgrades with x3 each;
Equip Up and Armor up would have 25 upgrades each with x2 each.

**Reason for change**
Currently we have really fast Rogue Legacy games that doesn't really match other games's length due to x5 upgrades, so a RL player could finish their seed in less than an hour while a second player playing HK for example would take over 2h to finish their seed.
This improved behavior would allow for longer and more balanced games, extending (and balancing) Rogue Legacy's games/races.
Also, it would only be an addition to the current system, and not a complete rework on the settings file.

**Comment by ThePhar** [comment]
Got something like this in my project tracker. Not 100% if I'll implement something exactly like this, but I do want to allow scaling of how fast stat upgrades work so the game can be reasonably scaled to accommodate games like Hollow Knight which can take 5+ hours.

Biggest obstacle is just having to take into account that would add a lot more location checks which is pretty bad in the current version, but I have a solution for that in my castle generation overhaul, so we'll see how it goes next version.

Thanks for the suggestion, will work on soon!

**Comment by zViitorEXCELLENT** [comment]
I see, thank you! Excited for the next version.

Best of luck on it!
