### ISSUE TITLE
[Issue] Game crashing on start after playing PasswordGame

### ISSUE THREAD

**Issue by Chaosicx** [ThePhar/RogueLegacyRandomizer#73]
**Describe the bug**
Rogue Legacy is crashing as soon as the game starts. The exception is `System.ArgumentException: An item with the same key has already been added.` This is happening after a ton of checks from three separate PasswordGame worlds were sent out.

**To Reproduce**
1. In RLR, log in to the `Chaosicx RL` slot for the following room and start the game: https://archipelago.gg/room/dKdEaEiSQjiWzWUE7DGUag

**Expected behavior**
The game does not crash.

**Desktop:**
 - RLR Version 0.9.3
 - AP Version 0.4.1
[CrashLog_07-07-2023_17-24-24.zip](https://github.com/ThePhar/RogueLegacyRandomizer/files/11986671/CrashLog_07-07-2023_17-24-24.zip)

**Comment by ThePhar** [comment]
Not RL issue, was a issue with Password game. Released an update for password that fixes this..
